title: "Benjamin R. Heiner"
email: "benheiner7@gmail.com"
description: >- 
  Chemist and surface scientist. This site showcases my research, CV, and publications.
baseurl: ""  # Leave empty for GitHub Pages
url: "https://benheiner7.github.io"  # Replace with your actual GitHub Pages URL if different

# Author details
author:
  name: "Benjamin R. Heiner"
  avatar: "/assets/images/Profile.jpg"
  bio: "###"
  location: "United States"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:benheiner7@gmail.com"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/benheiner"
    - label: "ORCID"
      icon: "ai ai-orcid"
      url: "https://orcid.org/0000-0002-2677-5184"

# Theme settings
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Markdown engine
markdown: kramdown
kramdown:
  input: GFM

# Enable plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Collections (optional for organizing content like research)
collections:
  research:
    output: true
    permalink: /research/:path/

# Default layout
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true

# Navigation bar
nav:
  - title: "Home"
    url: /
  - title: "CV"
    url: /cv/
  - title: "Research"
    url: /research/
  - title: "Contact"
    url: /contact/

# Logo and favicon (optional)
#logo: "/assets/images/logo.png"
#favicon: "/assets/images/favicon.ico"

